config/routes.rb
Rails.application.routes.draw do

  root to: 'products#index'

  resources :products, only: [:index, :show]
  resources :categories, only: [:show]
  resources :about, only: [:show] do
    root to: 'about#show'
  end
  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create]
  get '/logout' => 'sessions#destroy'

  resource :cart, only: [:show] do
    post   :add_item
    post   :remove_item
  end

  resources :orders, only: [:create, :show]

  namespace :admin do
    root to: 'dashboard#show'
    resources :products, except: [:edit, :update, :show]
    resources :categories, only: [:index, :new, :create]
    resources :sales, only: [:index, :new]
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password


  validate :passwords_match
  validates :email, presence: true, uniqueness: {case_sensitive: false}
  validates :password_digest, presence: true

  def passwords_match 
    if password != password_confirmation
      errors.add(:password_confirmation, 'Password fields must match')
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
    
  end
  def create
    user = User.new(user_params)
    if user.save 
      session[:user_id] = user.id
      redirect_to :root
      # raise current_user.inspect
    else
      redirect_to '/users/new' 
  end
end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/views/users/new.html.erb
<h1>Signup!</h1>

<%= form_for :user, url: '/users' do |f| %>

  <p>Email: <%= f.text_field :email %></p>
  <p> Password: <%= f.password_field :password %></p>
  <p> Password Confirmation: <%= f.password_field :password_confirmation %></p>
  
 
 
  <%= f.submit "Submit" %>
  <p><%= link_to 'Already have an account?', new_session_path %></p>

<% end %>